name: Wake Up Streamlit App

on:
  schedule:
    # 每一小时运行一次（北京时间每小时的 0 分左右）
    - cron: '0 */1 * * *'
  workflow_dispatch: # 允许手动点击按钮测试

jobs:
  ping_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./ping_app.sh

      - name: Run ping script
        run: ./ping_app.sh
